import { jsPDF } from 'jspdf';
import { StudyMaterial, CompareResult } from '../types';

function cleanText(text: string): string {
  if (!text) return '';
  return text
    .replace(/\*\*(.*?)\*\*/g, '$1')
    .replace(/\*(.*?)\*/g, '$1')
    .replace(/#{1,6}\s?/g, '')
    .replace(/\\frac\{([^}]+)\}\{([^}]+)\}/g, '($1/$2)')
    .replace(/\\sqrt\{([^}]+)\}/g, 'sqrt($1)')
    .replace(/\$+/g, '')
    .trim();
}

export function exportToTxt(material: StudyMaterial): void {
  const lines: string[] = [];
  lines.push(`AI STUDY ASSISTANT — ${material.topic.toUpperCase()}`);
  lines.push(`Difficulty: ${material.difficulty} | Study Mode: ${material.study_mode}`);
  lines.push('='.repeat(60));
  lines.push('');

  lines.push('EXPLANATION');
  lines.push('-'.repeat(60));
  lines.push(cleanText(material.explanation) || '(No explanation generated)');
  lines.push('');

  lines.push('SUMMARY');
  lines.push('-'.repeat(60));
  lines.push(cleanText(material.summary) || '(No summary generated)');
  lines.push('');

  lines.push('IMPORTANT POINTS');
  lines.push('-'.repeat(60));
  lines.push(cleanText(material.important_points) || '(No key points generated)');
  lines.push('');

  lines.push('QUIZ');
  lines.push('-'.repeat(60));
  if (material.quiz && material.quiz.length > 0) {
    material.quiz.forEach((q, idx) => {
      lines.push(`Q${idx + 1}. ${cleanText(q.question)}`);
      if (q.type === 'mcq' && q.options) {
        ['A', 'B', 'C', 'D'].forEach(letter => {
          if (q.options?.[letter]) {
            lines.push(`   ${letter}) ${q.options[letter]}`);
          }
        });
        lines.push(`   Answer: ${q.answer}`);
      } else {
        lines.push(`   Answer: ${cleanText(q.answer)}`);
      }
      lines.push('');
    });
  } else {
    lines.push('(No quiz generated)');
    lines.push('');
  }

  lines.push('='.repeat(60));
  lines.push('Generated by AI Study Assistant');

  const blob = new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${material.topic.toLowerCase().replace(/[^a-z0-9]+/g, '_')}_study_notes.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportToPdf(material: StudyMaterial): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 16;
  const contentWidth = pageWidth - margin * 2;
  let cursorY = 20;

  const checkPageBreak = (neededHeight: number) => {
    if (cursorY + neededHeight > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      cursorY = 20;
    }
  };

  // Header Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(30, 41, 59); // Slate 800
  doc.text(`AI Study Assistant: ${material.topic}`, margin, cursorY);
  cursorY += 8;

  // Metadata
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139); // Slate 500
  doc.text(`Difficulty: ${material.difficulty}  |  Study Mode: ${material.study_mode}  |  Generated: ${new Date().toLocaleDateString()}`, margin, cursorY);
  cursorY += 6;

  // Divider
  doc.setDrawColor(226, 232, 240);
  doc.line(margin, cursorY, pageWidth - margin, cursorY);
  cursorY += 8;

  const renderSection = (title: string, content: string) => {
    checkPageBreak(25);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(37, 99, 235); // Blue 600
    doc.text(title, margin, cursorY);
    cursorY += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85); // Slate 700
    const cleanLines = cleanText(content);
    const splitText = doc.splitTextToSize(cleanLines, contentWidth);
    
    splitText.forEach((line: string) => {
      checkPageBreak(6);
      doc.text(line, margin, cursorY);
      cursorY += 5.5;
    });

    cursorY += 5;
  };

  renderSection('📘 Explanation', material.explanation);
  renderSection('📝 Summary', material.summary);
  renderSection('⭐ Important Points', material.important_points);

  // Quiz section
  if (material.quiz && material.quiz.length > 0) {
    checkPageBreak(25);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(37, 99, 235);
    doc.text('🧠 Quiz', margin, cursorY);
    cursorY += 7;

    material.quiz.forEach((q, idx) => {
      checkPageBreak(18);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10.5);
      doc.setTextColor(30, 41, 59);
      const qText = doc.splitTextToSize(`Q${idx + 1}. ${cleanText(q.question)}`, contentWidth);
      doc.text(qText, margin, cursorY);
      cursorY += qText.length * 5;

      if (q.type === 'mcq' && q.options) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9.5);
        doc.setTextColor(71, 85, 105);
        ['A', 'B', 'C', 'D'].forEach(l => {
          if (q.options?.[l]) {
            checkPageBreak(5);
            doc.text(`    ${l}) ${q.options[l]}`, margin, cursorY);
            cursorY += 4.5;
          }
        });
        checkPageBreak(6);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(16, 185, 129); // Emerald
        doc.text(`    Correct Answer: ${q.answer}`, margin, cursorY);
        cursorY += 6;
      } else {
        checkPageBreak(6);
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(9.5);
        doc.setTextColor(16, 185, 129);
        const ansText = doc.splitTextToSize(`    Answer: ${cleanText(q.answer)}`, contentWidth - 5);
        doc.text(ansText, margin, cursorY);
        cursorY += ansText.length * 5 + 3;
      }
    });
  }

  const filename = `${material.topic.toLowerCase().replace(/[^a-z0-9]+/g, '_')}_study_notes.pdf`;
  doc.save(filename);
}

export function exportCompareToTxt(compare: CompareResult): void {
  const lines: string[] = [];
  lines.push(`AI STUDY ASSISTANT — COMPARE MODE`);
  lines.push(`${compare.topic_a.toUpperCase()}  VS  ${compare.topic_b.toUpperCase()}`);
  lines.push('='.repeat(60));
  lines.push('');

  lines.push('OVERVIEW');
  lines.push('-'.repeat(60));
  lines.push(cleanText(compare.overview));
  lines.push('');

  lines.push('SIMILARITIES');
  lines.push('-'.repeat(60));
  lines.push(cleanText(compare.similarities));
  lines.push('');

  lines.push('KEY DIFFERENCES');
  lines.push('-'.repeat(60));
  lines.push(cleanText(compare.differences));
  lines.push('');

  lines.push('WHEN TO USE WHICH');
  lines.push('-'.repeat(60));
  lines.push(cleanText(compare.use_cases));
  lines.push('');

  lines.push('QUICK SUMMARY');
  lines.push('-'.repeat(60));
  lines.push(cleanText(compare.summary));
  lines.push('');

  lines.push('='.repeat(60));
  lines.push('Generated by AI Study Assistant — Compare Mode');

  const blob = new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `compare_${compare.topic_a}_vs_${compare.topic_b}.txt`.toLowerCase().replace(/[^a-z0-9._]+/g, '_');
  a.click();
  URL.revokeObjectURL(url);
}

export function exportCompareToPdf(compare: CompareResult): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 16;
  const contentWidth = pageWidth - margin * 2;
  let cursorY = 20;

  const checkPageBreak = (neededHeight: number) => {
    if (cursorY + neededHeight > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      cursorY = 20;
    }
  };

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(30, 41, 59);
  doc.text(`Compare: ${compare.topic_a} vs ${compare.topic_b}`, margin, cursorY);
  cursorY += 8;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(`Generated by AI Study Assistant  |  ${new Date().toLocaleDateString()}`, margin, cursorY);
  cursorY += 6;

  doc.setDrawColor(226, 232, 240);
  doc.line(margin, cursorY, pageWidth - margin, cursorY);
  cursorY += 8;

  const renderSection = (title: string, content: string) => {
    checkPageBreak(25);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(99, 102, 241); // Indigo 500
    doc.text(title, margin, cursorY);
    cursorY += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    const splitText = doc.splitTextToSize(cleanText(content), contentWidth);
    splitText.forEach((line: string) => {
      checkPageBreak(6);
      doc.text(line, margin, cursorY);
      cursorY += 5.5;
    });
    cursorY += 5;
  };

  renderSection('🔍 Overview', compare.overview);
  renderSection('🤝 Similarities', compare.similarities);
  renderSection('⚡ Key Differences', compare.differences);
  renderSection('🎯 When to Use Which', compare.use_cases);
  renderSection('📌 Quick Summary', compare.summary);

  const filename = `compare_${compare.topic_a}_vs_${compare.topic_b}.pdf`.toLowerCase().replace(/[^a-z0-9._]+/g, '_');
  doc.save(filename);
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (err) {
    console.error('Failed to copy to clipboard:', err);
    return false;
  }
}
